const Operator = {
	Plus: '+',
	Minus: '-',
	Multiply: '*',
	Divide: '/',
	Modulus: '%',
	LessThan: '<',
	GreaterThan: '>',
	LessThanOrEqual: '<=',
	GreaterThanOrEqual: '>=',
	Equal: '==',
	NotEqual: '!=',
	ApproxEqual: '~=',
	And: '&&',
	Or: '||',
	Not: '!',
	Assignment: '=',
	Increment: '++',
	Decrement: '--',
	UnaryPlus: '+',
	UnaryMinus: '-',
	AddEqual: '+=',
	SubtractEqual: '-=',
	MultiplyEqual: '*=',
	DivideEqual: '/=',
	ModulusEqual: '%=',
};

module.exports = Operator;